version: "3"

services:

  web:
      image: webdevops/php-nginx-dev:7.2
      volumes:
          - ./:/app
      working_dir: /app
      depends_on:
          - database
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          WEB_DOCUMENT_INDEX: index.php
          PHP_DATE_TIMEZONE: "UTC"
          PHP_DISPLAY_ERRORS: 1

  database:
      image: mysql:5.7
      volumes:
          - ./docker/database:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydatabase
